<?php
/**
 * Defines the module management hooks required by Drupal.
 *
 * @author     Bastian Feder <drupal@bastian-feder.de>
 * @license    http://www.opensource.org/licenses/mit-license.php The MIT License
 * @copyright  Copyright (c) 2012 Liip inc.
 */


function DrupalCrudAdminModule_install()
{

}

function DrupalCrudAdminModule_uninstall()
{

}

function DrupalCrudAdminModule_enable()
{

}

function DrupalCrudAdminModule_disable()
{

}

